# Lecture 3 - NumPy


## NumPy
- Most common package for scientific computing with Python
- Its fundamental object is `np.array`, an multidimensional array of numbers
- Provides linear algebra, Fourier transform, random number capabilities
- Building block for other packages (e.g. SciPy, scikit-learn)
- Open source, huge dev community!

In [1]:
import numpy as np

In [3]:
python_list = [1, 2, 3]

In [4]:
np.array(python_list)

array([1, 2, 3])

In [6]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [7]:
arr = np.array([2**i for i in [2, 3, 9]])
arr

array([  4,   8, 512])

In [9]:
arr = np.array([2**i for i in range(10) if i != 5])
arr

array([  1,   2,   4,   8,  16,  64, 128, 256, 512])

### 1. Exercise
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [17]:
arr = np.array([i for i in range(1, 100, 1) if str(2**i).endswith('6')])
arr

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
       72, 76, 80, 84, 88, 92, 96])

In [22]:
arr = np.array([ i for i in range(100) if 2**i % 10 == 6 ],dtype=np.int)
arr

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
       72, 76, 80, 84, 88, 92, 96])

In [15]:
arr = np.array([(i, 2**i) for i in range(1, 100, 1) if str(2**i).endswith('6')])
arr


array([[4, 16],
       [8, 256],
       [12, 4096],
       [16, 65536],
       [20, 1048576],
       [24, 16777216],
       [28, 268435456],
       [32, 4294967296],
       [36, 68719476736],
       [40, 1099511627776],
       [44, 17592186044416],
       [48, 281474976710656],
       [52, 4503599627370496],
       [56, 72057594037927936],
       [60, 1152921504606846976],
       [64, 18446744073709551616],
       [68, 295147905179352825856],
       [72, 4722366482869645213696],
       [76, 75557863725914323419136],
       [80, 1208925819614629174706176],
       [84, 19342813113834066795298816],
       [88, 309485009821345068724781056],
       [92, 4951760157141521099596496896],
       [96, 79228162514264337593543950336]], dtype=object)

In [21]:
A = [[i*j for i in range(j)] for j in range(10)]
A

[[],
 [0],
 [0, 2],
 [0, 3, 6],
 [0, 4, 8, 12],
 [0, 5, 10, 15, 20],
 [0, 6, 12, 18, 24, 30],
 [0, 7, 14, 21, 28, 35, 42],
 [0, 8, 16, 24, 32, 40, 48, 56],
 [0, 9, 18, 27, 36, 45, 54, 63, 72]]

## Vectorization

In [ ]:
def fn(x):
    