# Lecture 3 - NumPy


## NumPy
- Most common package for scientific computing with Python
- Its fundamental object is `np.array`, an multidimensional array of numbers
- Provides linear algebra, Fourier transform, random number capabilities
- Building block for other packages (e.g. SciPy, scikit-learn)
- Open source, huge dev community!

In [2]:
import numpy as np

In [3]:
python_list = [1, 2, 3]

In [4]:
np.array(python_list)

array([1, 2, 3])

In [6]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [7]:
arr = np.array([2**i for i in [2, 3, 9]])
arr

array([  4,   8, 512])

In [9]:
arr = np.array([2**i for i in range(10) if i != 5])
arr

array([  1,   2,   4,   8,  16,  64, 128, 256, 512])

### 1. Exercise
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [17]:
arr = np.array([i for i in range(1, 100, 1) if str(2**i).endswith('6')])
arr

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
       72, 76, 80, 84, 88, 92, 96])

In [22]:
arr = np.array([ i for i in range(100) if 2**i % 10 == 6 ],dtype=np.int)
arr

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
       72, 76, 80, 84, 88, 92, 96])

In [15]:
arr = np.array([(i, 2**i) for i in range(1, 100, 1) if str(2**i).endswith('6')])
arr


array([[4, 16],
       [8, 256],
       [12, 4096],
       [16, 65536],
       [20, 1048576],
       [24, 16777216],
       [28, 268435456],
       [32, 4294967296],
       [36, 68719476736],
       [40, 1099511627776],
       [44, 17592186044416],
       [48, 281474976710656],
       [52, 4503599627370496],
       [56, 72057594037927936],
       [60, 1152921504606846976],
       [64, 18446744073709551616],
       [68, 295147905179352825856],
       [72, 4722366482869645213696],
       [76, 75557863725914323419136],
       [80, 1208925819614629174706176],
       [84, 19342813113834066795298816],
       [88, 309485009821345068724781056],
       [92, 4951760157141521099596496896],
       [96, 79228162514264337593543950336]], dtype=object)

In [21]:
A = [[i*j for i in range(j)] for j in range(10)]
A

[[],
 [0],
 [0, 2],
 [0, 3, 6],
 [0, 4, 8, 12],
 [0, 5, 10, 15, 20],
 [0, 6, 12, 18, 24, 30],
 [0, 7, 14, 21, 28, 35, 42],
 [0, 8, 16, 24, 32, 40, 48, 56],
 [0, 9, 18, 27, 36, 45, 54, 63, 72]]

## Vectorization

In [1]:
def fn(x):
    return x*x + 4*x + 5

In [2]:
fn(10)

145

In [5]:
fn(np.linspace(0,1,10))

array([ 5.        ,  5.45679012,  5.9382716 ,  6.44444444,  6.97530864,
        7.5308642 ,  8.11111111,  8.71604938,  9.34567901, 10.        ])

### 2. Exercise
Create an array of first 10 powers of 2

In [7]:
[2**i for i in range(10)] # this is a list not an array

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [8]:
2**np.arange(10)

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

## Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [3]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
3 * np.ones((8,8)) + 11

array([[14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14.]])

In [6]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [12]:
np.arange(10).reshape(10,1) * np.ones((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

### Distinction between numpy 1D arrays and numpy 2D arrays

This tends to cause a lot of confusion for new numpy users.
Follow the below examples carefully to understand the distinction.

In [14]:
X = np.arange(10)
print(X)
print(X.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [15]:
Y = np.arange(10).reshape(-1,1)
print(Y)
print(Y.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [18]:
Z = np.arange(10).reshape(1,-1)
print(Z)
print(Z.shape)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [19]:
Z.squeeze()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
Mat = np.random.randn(10,10)

In [21]:
Mat @ X

array([ 10.63501119, -12.63569925,   7.15145851,  16.91693689,
         3.11357212,   1.50983065,   8.03375747, -27.05593974,
        -9.26625714, -25.86318667])

## Array Broadcasting

Normally you only do arithmetic operations between arrays of the same dimension

In [22]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
np.ones((5,5,5)) + np.arange(5*5*5).reshape(5,5,5)

array([[[  1.,   2.,   3.,   4.,   5.],
        [  6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.,  25.]],

       [[ 26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.],
        [ 36.,  37.,  38.,  39.,  40.],
        [ 41.,  42.,  43.,  44.,  45.],
        [ 46.,  47.,  48.,  49.,  50.]],

       [[ 51.,  52.,  53.,  54.,  55.],
        [ 56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.],
        [ 66.,  67.,  68.,  69.,  70.],
        [ 71.,  72.,  73.,  74.,  75.]],

       [[ 76.,  77.,  78.,  79.,  80.],
        [ 81.,  82.,  83.,  84.,  85.],
        [ 86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.],
        [ 96.,  97.,  98.,  99., 100.]],

       [[101., 102., 103., 104., 105.],
        [106., 107., 108., 109., 110.],
        [111., 112., 113., 114., 115.],
        [116., 117., 118., 119., 120.],
        [121., 122., 123., 124.,

In [26]:
np.ones((5,5,5)) + np.arange(5).reshape(5,1,1)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [30]:
np.ones((1,5,5)) + np.ones((5,1,5))

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

### 3. Exercise
create a 2D numpy array $A$ such that $A_{ij} = i\times j$, but without using list comprehensions. Use broadcasting instead

In [73]:
i = 7
j = 11
A = (1 + np.arange(i).reshape(i, -1)) * (np.ones(j) + np.arange(j))
print(A)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63. 70. 77.]]


### 4. Exercise
Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [86]:
i = 10
j = 10
A = 2 ** (1 + np.arange(i).reshape(i, -1)) + (np.ones(j) + np.arange(j))
print(A)

[[   3.    4.    5.    6.    7.    8.    9.   10.   11.   12.]
 [   5.    6.    7.    8.    9.   10.   11.   12.   13.   14.]
 [   9.   10.   11.   12.   13.   14.   15.   16.   17.   18.]
 [  17.   18.   19.   20.   21.   22.   23.   24.   25.   26.]
 [  33.   34.   35.   36.   37.   38.   39.   40.   41.   42.]
 [  65.   66.   67.   68.   69.   70.   71.   72.   73.   74.]
 [ 129.  130.  131.  132.  133.  134.  135.  136.  137.  138.]
 [ 257.  258.  259.  260.  261.  262.  263.  264.  265.  266.]
 [ 513.  514.  515.  516.  517.  518.  519.  520.  521.  522.]
 [1025. 1026. 1027. 1028. 1029. 1030. 1031. 1032. 1033. 1034.]]
