# Exercício 1

**Nome:** Angela Crepaldi

In [1]:
# Bibliotecas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# 1. Manipulando arrays

1. Escreva uma função do Python que implementa a [similaridade do cosseno](https://en.wikipedia.org/wiki/Cosine_similarity) (eq. A.7 do Watt) entre dois vetores, definida por

$$
{\rm cosine\_similarity(\boldsymbol{x},\boldsymbol{y})} = \frac{\boldsymbol{x}^T \boldsymbol{y}}{\|\boldsymbol{x}\|\|\boldsymbol{y}\|}
$$

In [2]:
# Solução

def cosine_similarity(x,y):
    s = (np.transpose(x) @ y) / (np.linalg.norm(x) * np.linalg.norm(y))
    return s

# Testes
x = np.array([1,2,3,4])
y = np.array([2,2,2,2])
z = np.array([2,-2,2,-2])
print(cosine_similarity(x,y)) # = 0.9128709291752769
print(cosine_similarity(x,z)) # = -0.18257418583505536

0.9128709291752769
-0.18257418583505536


2. Calcule os produtos $\bA^T\bB$ e $\bB \bA^T$, onde
$$\bA = \mat{1 & 2 \\ 3 & 4 \\ 5 & 6} \qquad \bB = \mat{1 & 1 \\ 1 & 1 \\ 1 & 1}$$

In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
B = np.ones((3, 2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.transpose(A) @ B

array([[ 9.,  9.],
       [12., 12.]])

In [8]:
np.transpose(B) @ A

array([[ 9., 12.],
       [ 9., 12.]])

3. Considere os vetores abaixo.

In [9]:
A = np.array([[1,0,1],[0,1,0],[1,1,1]])
A

array([[1, 0, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [10]:
b = np.array([1,2,3])
b

array([1, 2, 3])

Explique o porquê do resultado abaixo.

In [11]:
np.all(b*A == A*b)

True

Resposta:

A função np.all() testa se todos os elementos da matriz são verdadeiros, neste caso, a matriz é o resultado da comparação entre $b*A$ e $A*b$ cujos elementos correspondentes são iguais. 

A operação $*$ no python faz uma multiplicação elemento a elemento. Para ser uma multiplicação entre arrays, é necessário utilizar o produto interno, np.dot(A, b), ou o operador @.

In [12]:
b*A

array([[1, 0, 3],
       [0, 2, 0],
       [1, 2, 3]])

In [13]:
A*b

array([[1, 0, 3],
       [0, 2, 0],
       [1, 2, 3]])

In [18]:
np.dot(A, b)

array([4, 2, 6])

In [19]:
np.dot(b, A)

array([4, 5, 4])

In [20]:
A @ b

array([4, 2, 6])

In [21]:
b @ A

array([4, 5, 4])